# Generated by Django 5.2.4 on 2025-10-01 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('incidencia_id', models.BigAutoField(db_column='Incidencia_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='Descripción', null=True)),
                ('departamento', models.ForeignKey(db_column='Departamento_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='orgs.departamento')),
                ('direccion', models.ForeignKey(db_column='Direccion_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='orgs.direccion')),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencia',
                'db_table': 'Incidencia',
                'indexes': [models.Index(fields=['nombre'], name='incidencia_nombre_idx')],
            },
        ),
    ]
