# Generated by Django 5.2.4 on 2025-10-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="incidencia",
            table="catalogs_incidencia",
        ),
    ]
