# Generated by Django 5.2.4 on 2025-10-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0002_alter_incidencia_table"),
        ("surveys", "0004_remove_encuesta_incidencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="encuesta",
            field=models.ForeignKey(
                blank=True,
                db_column="Encuesta_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidencias",
                to="surveys.encuesta",
            ),
        ),
    ]
