# Generated by Django 5.2.4 on 2025-10-15 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0004_incidencia_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidencia",
            name="estado",
        ),
    ]
