# Generated by Django 5.2.4 on 2025-10-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0005_remove_incidencia_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="estado",
            field=models.BooleanField(db_column="Estado", default=True),
        ),
    ]
