# Generated by Django 5.2.4 on 2025-10-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0003_alter_cuadrilla_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="direccion",
            name="estado",
            field=models.CharField(default="Activo", max_length=20),
        ),
    ]
