# Generated by Django 5.2.4 on 2025-10-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_direccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
