# Generated by Django 5.2.4 on 2025-10-17 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_secpla'),
        ('registration', '0002_profile_mobile_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secpla',
            options={'ordering': ['nombre'], 'verbose_name': 'Secpla', 'verbose_name_plural': 'Secplas'},
        ),
        migrations.RemoveField(
            model_name='cuadrilla',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='secpla',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='territorial',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas', to='registration.profile'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='registration.profile'),
        ),
        migrations.AddField(
            model_name='secpla',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secplas', to='registration.profile'),
        ),
        migrations.AddField(
            model_name='territorial',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='territoriales', to='registration.profile'),
        ),
    ]
