# Generated by Django 5.2.4 on 2025-10-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_secpla_options_remove_cuadrilla_usuario_and_more'),
        ('registration', '0003_profile_role_object_id_profile_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='profile',
            field=models.ForeignKey(blank=True, db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='registration.profile'),
        ),
    ]
