# Generated by Django 5.2.4 on 2025-10-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_departamento_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.BooleanField(db_column='Estado', default=True),
        ),
    ]
