# Generated by Django 5.2.4 on 2025-10-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_mobile_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_type',
            field=models.CharField(blank=True, choices=[('secpla', 'Secpla'), ('direccion', 'Dirección'), ('departamento', 'Departamento'), ('cuadrilla', 'Cuadrilla'), ('territorial', 'Territorial')], max_length=20, null=True),
        ),
    ]
