# Generated by Django 5.2.4 on 2025-10-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=240)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['prioridad', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('encuesta', models.ForeignKey(db_column='Encuesta_id', on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='surveys.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(db_column='Pregunta_id', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='surveys.pregunta')),
            ],
        ),
    ]
