# Generated by Django 5.2.4 on 2025-10-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='solicitud_incidencia',
            field=models.ForeignKey(db_column='Solicitud_Incidencia_ID', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='tickets.solicitudincidencia'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('solicitud_incidencia', 'pregunta'), name='unique_respuesta_por_pregunta_solicitud'),
        ),
    ]
