# Generated by Django 5.2.4 on 2025-10-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0002_alter_incidencia_table"),
        ("surveys", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuesta",
            name="incidencia",
            field=models.ForeignKey(
                blank=True,
                db_column="Incidencia_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encuestas",
                to="catalogs.incidencia",
            ),
        ),
    ]
