# Generated by Django 5.2.4 on 2025-10-06 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_encuesta_incidencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encuesta",
            name="incidencia",
        ),
    ]
