# Generated by Django 5.2.4 on 2025-10-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_remove_encuesta_incidencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuesta",
            name="prioridad",
            field=models.CharField(
                choices=[("Alta", "Alta"), ("Media", "Media"), ("Baja", "Baja")],
                default="Media",
                max_length=20,
            ),
        ),
    ]
