# Generated by Django 5.2.4 on 2025-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0005_alter_encuesta_prioridad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuesta",
            name="prioridad",
            field=models.CharField(
                blank=True,
                choices=[("Alta", "Alta"), ("Media", "Media"), ("Baja", "Baja")],
                max_length=20,
                null=True,
            ),
        ),
    ]
