# Generated by Django 5.2.4 on 2025-11-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_encuesta_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
    ]
