# Generated by Django 5.2.4 on 2025-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='tipo_incidencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Incidencia'),
        ),
    ]
