# Generated by Django 5.2.4 on 2025-11-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_encuesta_tipo_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fue_borrado',
            field=models.BooleanField(default=False),
        ),
    ]
