# Generated by Django 5.2.4 on 2025-09-28 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido', regex='^\\+?\\d{7,15}$')])),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido')])),
            ],
        ),
    ]
