# Generated by Django 5.2.4 on 2025-10-01 02:33

import django.core.validators
import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('numero_casa', models.CharField(max_length=20)),
                ('latitud', models.FloatField(blank=True, null=True, validators=[locations.models.validar_latitud])),
                ('longitud', models.FloatField(blank=True, null=True, validators=[locations.models.validar_longitud])),
            ],
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido', regex='^\\+?\\d{7,15}$')])),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido')])),
            ],
        ),
    ]
