# Generated by Django 5.2.4 on 2025-11-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('tickets', '0008_alter_solicitudincidencia_vecino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vecino',
        ),
    ]
