# Generated by Django 5.2.4 on 2025-10-03 02:16

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('locations', '0001_initial'),
        ('orgs', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIncidencia',
            fields=[
                ('solicitud_incidencia_id', models.BigAutoField(db_column='Solicitud_Incidencia_ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='Descripción', null=True)),
                ('fecha', models.DateTimeField(db_column='Fecha', default=django.utils.timezone.now)),
                ('cuadrilla', models.ForeignKey(db_column='Cuadrilla_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='orgs.cuadrilla')),
                ('encuesta', models.ForeignKey(db_column='Encuesta_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='surveys.encuesta')),
                ('incidencia', models.ForeignKey(db_column='Incidencia_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogs.incidencia')),
                ('territorial', models.ForeignKey(db_column='Territorial_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='orgs.territorial')),
                ('ubicacion', models.ForeignKey(db_column='Ubicacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='locations.ubicacion')),
                ('vecino', models.ForeignKey(db_column='Vecino_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='locations.vecino')),
            ],
            options={
                'verbose_name': 'Solicitud de Incidencia',
                'verbose_name_plural': 'Solicitudes de Incidencia',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('multimedia_id', models.BigAutoField(db_column='Multimedia_ID', primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias/', validators=[tickets.models.validar_tipo_archivo])),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('solicitud_incidencia', models.ForeignKey(db_column='Solicitud_incidencia_id', on_delete=django.db.models.deletion.PROTECT, related_name='multimedia', to='tickets.solicitudincidencia')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoEncuesta',
            fields=[
                ('historial_id', models.BigAutoField(db_column='Historial_Estado_ID', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('usuario', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(db_column='Solicitud_Incidencia_ID', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tickets.solicitudincidencia')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
            },
        ),
    ]
