# Generated by Django 5.2.4 on 2025-10-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('orgs', '0010_alter_cuadrilla_estado_alter_direccion_estado'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, db_column='Cuadrilla_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='orgs.cuadrilla'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='territorial',
            field=models.ForeignKey(blank=True, db_column='Territorial_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='orgs.territorial'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_column='Ubicacion_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='locations.ubicacion'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='vecino',
            field=models.ForeignKey(blank=True, db_column='Vecino_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_incidencia', to='locations.vecino'),
        ),
    ]
