# Generated by Django 5.2.4 on 2025-10-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_solicitudincidencia_cuadrilla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudincidencia",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, db_column="Fecha_inicio", null=True),
        ),
    ]
