# Generated by Django 5.2.4 on 2025-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_solicitudincidencia_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Derivada', 'Derivada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], db_column='Estado', default='Pendiente', max_length=50),
        ),
    ]
