# Generated by Django 5.2.4 on 2025-10-22 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_role_object_id_profile_role_type'),
        ('tickets', '0005_alter_solicitudincidencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='Incidencia_Log_ID', primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(db_column='Desde', max_length=50)),
                ('estado_actual', models.CharField(db_column='Hasta', max_length=50)),
                ('fecha', models.DateTimeField(db_column='Fecha', default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, db_column='Nota', null=True)),
                ('profile', models.ForeignKey(db_column='Usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidencia_logs', to='registration.profile')),
                ('solicitud', models.ForeignKey(db_column='Solicitud_Incidencia_ID', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='tickets.solicitudincidencia')),
            ],
            options={
                'verbose_name': 'Log de Incidencia',
                'verbose_name_plural': 'Logs de Incidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='HistorialEstadoEncuesta',
        ),
    ]
