# Generated by Django 5.2.4 on 2025-10-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_incidencialog_delete_historialestadoencuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencialog',
            old_name='estado_anterior',
            new_name='from_estado',
        ),
        migrations.RenameField(
            model_name='incidencialog',
            old_name='estado_actual',
            new_name='to_estado',
        ),
    ]
