# Generated by Django 5.2.4 on 2025-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_estado_anterior_incidencialog_from_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='vecino',
            field=models.TextField(),
        ),
    ]
