# Generated by Django 5.1.13 on 2025-11-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_incidencia_estado'),
        ('tickets', '0009_alter_solicitudincidencia_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='incidencia',
            field=models.ForeignKey(db_column='Incidencia_id', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogs.incidencia'),
        ),
    ]
