# Generated by Django 5.2.4 on 2025-11-11 16:40

import django.db.models.deletion
import django.utils.timezone
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_remove_cuadrilla_profile_remove_departamento_profile_and_more'),
        ('tickets', '0010_alter_solicitudincidencia_incidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCuadrilla',
            fields=[
                ('respuesta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_cuadrilla', to='orgs.cuadrilla')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuadrilla', to='tickets.solicitudincidencia')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_cuadrilla/', validators=[tickets.models.validar_tipo_archivo])),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='tickets.respuestacuadrilla')),
            ],
        ),
    ]
