# Generated by Django 5.2.4 on 2025-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_solicitudincidencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='motivo',
            field=models.CharField(choices=[('Insuficiente', 'Insuficiente'), ('Incompleto', 'Incompleto'), ('Por mejorar', 'Por mejorar'), ('Otro motivo', 'Otro motivo')], db_column='Motivo', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='otro',
            field=models.TextField(default='no hay'),
            preserve_default=False,
        ),
    ]
