# Generated by Django 5.2.4 on 2025-11-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_change_ubicacion_to_text'),
        ('tickets', '0014_solicitudincidencia_motivo_solicitudincidencia_otro'),
    ]

    operations = [
    ]
